from setuptools import setup

setup(
    name="drdmannturb",
    version="0.1.0",
    description="Mann turbulence modelling",
    url="https://github.com/mjachi/DRDMannTurb",
    author="Alexey Izmailov, Matthew Meeker based on code by Brendan Keith et al",
    author_email="alizma@brown.edu, matthew_meeker@brown.edu",
    license="BSD 2-clause",
    packages=["drdmannturb"],
    install_requires=[
        "torch",
        "numpy",
        "tqdm",
        "scipy",
        "matplotlib",
        "pyevtk",
        "pyfftw",
        "tensorboard",
    ],
    extras_require={
        "dev": ["ruff", "isort", "black", "pytest", "pytest-cov"],
        "docs": [
            "ipython",
            "numpydoc",
            "pydocstyle",
            "Sphinx>=1.8.3",
            "pydata-sphinx-theme>=0.14.2",
            "sphinx-panels",
            "sphinx-notfound-page",
            "sphinx-copybutton",
            "sphinxcontrib-mermaid",
            "sphinxcontrib-jsmath",
            "nbsphinx",
            "sphinx-gallery",
            "myst_parser",
            "tensorboard",
        ],
    },
    classifiers=[
        "Development Status :: 1 - Planning",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: BSD License",
        "Operating System :: POSIX :: Linux",
        "Programming Language :: Python :: 3.9",
    ],
)
