name: drdmannturb_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.16
  - pytorch
  - isort
  - black
  - scipy
  - numpy = 1.26.4
  - matplotlib
  - plotly
  - sphinx
  - pyfftw
  - ipykernel
  - tensorboard
  - pytest
  - ruff[version='>=0.4.8']
  - pyevtk
  - pytest-cov
  - netcdf4
  - pandas
  - tqdm=4.66.4
  - scikit-learn
