name: Coverage Report

on:
  workflow_run:
    workflows: ["Tests"]
    types: [completed]

jobs:
  coverage:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          version: "latest"

      - name: Install dependencies
        run: uv sync --frozen

      - name: Install package
        run: uv pip install -e .

      - name: Install test dependencies
        run: uv add --dev pytest pytest-cov pytest-group

      - name: Generate coverage report
        run: uv run pytest test/ -v --cov=drdmannturb --cov-report=html --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: false
