name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          version: "latest"

      - name: Install dependencies
        run: uv sync --frozen

      - uses: astral-sh/ruff-action@v3
        with:
          src: "./drdmannturb"
          args: "check --fix --exclude=drdmannturb/examples-unrendered"

      - uses: astral-sh/ruff-action@v3
        with:
          src: "./drdmannturb"
          args: "format"
