name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: chartboost/ruff-action@v1
        with:
          src: "./drdmannturb"
          args: "--fix"

      - uses: jpetrucciani/mypy-check@master
        with:
          src: "./drdmannturb"
          args: "--ignore-missing-imports"
