name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install mypy data-science-types types-PyYAML

      - uses: astral-sh/ruff-action@v3
        with:
          src: "./drdmannturb"
          args: "check --fix --exclude=drdmannturb/examples-unrendered"

      - uses: astral-sh/ruff-action@v3
        with:
          src: "./drdmannturb"
          args: "format"
