name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/ruff-action@v3
        with:
          src: "./drdmannturb"
          args: "check --fix --exclude=drdmannturb/examples-unrendered"

      - uses: astral-sh/ruff-action@v3
        with:
          src: "./drdmannturb"
          args: "format"

      - uses: jpetrucciani/mypy-check@master
        with:
          src: "./drdmannturb"
          args: "--ignore-missing-imports"
