name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install your project dependencies (adjust path if needed)
          # If you have different files for prod/dev, install both
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          # Install mypy itself and common stubs
          # data-science-types includes numpy, pandas, matplotlib, scipy
          # Add others like types-torch if needed
          pip install mypy data-science-types types-PyYAML # Add types-plotly etc. if used heavily and stubs exist

      - uses: astral-sh/ruff-action@v3
        with:
          src: "./drdmannturb"
          args: "check --fix --exclude=drdmannturb/examples-unrendered"

      - uses: astral-sh/ruff-action@v3
        with:
          src: "./drdmannturb"
          args: "format"

      - name: Run Mypy
        run: |
          mypy ./drdmannturb --ignore-missing-imports
