name: Tests 

on: [push, pull_request]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: 
          python-version : '3.9'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt

      - name: Install package
        run: | 
          pip install .

      - name: Run tests
        run: | 
          pip install pytest
          python -m pytest 