name: Slow Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  slow-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          version: "latest"

      - name: Install dependencies
        run: uv sync --frozen

      - name: Install package
        run: uv pip install -e .

      - name: Install test dependencies
        run: uv add --dev pytest pytest-cov pytest-group

      - name: Run slow tests
        run: uv run pytest test/ --runslow -v
